from enum import Enum

class InventoryFirstTableEnum(Enum):
    DEMAND = "DEMAND"
    FREQUENCE = "FREQUENCE"
    PROBABILITY = "PROBABILITY"
    CUMULATIVEP_ROBABILITY = "CUMULATIVEP_ROBABILITY"
    INTERVAL_OF_RANDOM_NUMBERS = "INTERVAL_OF_RANDOM_NUMBERS"
